
-- ===========================================================================
-- Full exam catalog — 4 families, 43 exams, 122 stages, 30 default configs.
-- Generated from Exam_Pattern_Base_Configurations.xlsx. Idempotent (ON CONFLICT DO NOTHING).
-- Ids are stable readable strings (same convention as the rows above).
-- Mode->disposition & section->subject mappings documented in docs/seed-exam-catalog.md.
-- ===========================================================================

INSERT INTO "Subject" ("id","name","code") VALUES
  ('subject_reasoning','GENERAL INTELLIGENCE AND REASONING','REASONING'),
  ('subject_quantitative','QUANTITATIVE APTITUDE','QUANTITATIVE_APTITUDE'),
  ('subject_gk','GENERAL AWARENESS','GENERAL_AWARENESS'),
  ('subject_english','ENGLISH COMPREHENSION','ENGLISH'),
  ('subject_science','GENERAL SCIENCE','GENERAL_SCIENCE'),
  ('subject_general_studies','GENERAL STUDIES','GENERAL_STUDIES'),
  ('subject_computer','COMPUTER KNOWLEDGE','COMPUTER_KNOWLEDGE')
ON CONFLICT DO NOTHING;

INSERT INTO "Exam" ("id","family","code","name") VALUES
  ('exam_ssc_cgl','SSC','SSC_CGL','SSC CGL'),
  ('exam_ssc_chsl','SSC','SSC_CHSL','SSC CHSL'),
  ('exam_ssc_mts_havaldar','SSC','SSC_MTS_HAVALDAR','SSC MTS & Havaldar'),
  ('exam_ssc_gd_constable','SSC','SSC_GD_CONSTABLE','SSC GD Constable'),
  ('exam_ssc_cpo_si_in_delhi_police_capfs','SSC','SSC_CPO_SI_IN_DELHI_POLICE_CAPFS','SSC CPO (SI in Delhi Police & CAPFs)'),
  ('exam_ssc_je_junior_engineer','SSC','SSC_JE_JUNIOR_ENGINEER','SSC JE (Junior Engineer)'),
  ('exam_ssc_stenographer_grade_c_d','SSC','SSC_STENOGRAPHER_GRADE_C_D','SSC Stenographer (Grade C & D)'),
  ('exam_ssc_selection_post_phase_exams','SSC','SSC_SELECTION_POST_PHASE_EXAMS','SSC Selection Post (Phase Exams)'),
  ('exam_ssc_jht_junior_hindi_translator','SSC','SSC_JHT_JUNIOR_HINDI_TRANSLATOR','SSC JHT (Junior Hindi Translator)'),
  ('exam_rrb_ntpc_graduate_level','RRB','RRB_NTPC_GRADUATE_LEVEL','RRB NTPC (Graduate Level)'),
  ('exam_rrb_ntpc_undergraduate_level','RRB','RRB_NTPC_UNDERGRADUATE_LEVEL','RRB NTPC (Undergraduate Level)'),
  ('exam_rrb_group_d_level_1','RRB','RRB_GROUP_D_LEVEL_1','RRB Group D (Level 1)'),
  ('exam_rrb_alp_assistant_loco_pilot','RRB','RRB_ALP_ASSISTANT_LOCO_PILOT','RRB ALP (Assistant Loco Pilot)'),
  ('exam_rrb_je_junior_engineer','RRB','RRB_JE_JUNIOR_ENGINEER','RRB JE (Junior Engineer)'),
  ('exam_rrb_rpf_constable','RRB','RRB_RPF_CONSTABLE','RRB RPF Constable'),
  ('exam_rrb_rpf_si_sub_inspector','RRB','RRB_RPF_SI_SUB_INSPECTOR','RRB RPF SI (Sub-Inspector)'),
  ('exam_rrb_technician','RRB','RRB_TECHNICIAN','RRB Technician'),
  ('exam_rrb_ministerial_isolated_categories','RRB','RRB_MINISTERIAL_ISOLATED_CATEGORIES','RRB Ministerial & Isolated Categories'),
  ('exam_rrb_paramedical_categories','RRB','RRB_PARAMEDICAL_CATEGORIES','RRB Paramedical Categories'),
  ('exam_ibps_po_mt','BANKING','IBPS_PO_MT','IBPS PO / MT'),
  ('exam_ibps_clerk_crp_csa','BANKING','IBPS_CLERK_CRP_CSA','IBPS Clerk (CRP CSA)'),
  ('exam_ibps_so_specialist_officer','BANKING','IBPS_SO_SPECIALIST_OFFICER','IBPS SO (Specialist Officer)'),
  ('exam_ibps_rrb_crp_rrbs','BANKING','IBPS_RRB_CRP_RRBS','IBPS RRB (CRP RRBs)'),
  ('exam_sbi_po_probationary_officer','BANKING','SBI_PO_PROBATIONARY_OFFICER','SBI PO (Probationary Officer)'),
  ('exam_sbi_clerk_junior_associate','BANKING','SBI_CLERK_JUNIOR_ASSOCIATE','SBI Clerk (Junior Associate)'),
  ('exam_sbi_so_specialist_officer','BANKING','SBI_SO_SPECIALIST_OFFICER','SBI SO (Specialist Officer)'),
  ('exam_rbi_grade_b_dr_general','BANKING','RBI_GRADE_B_DR_GENERAL','RBI Grade B (DR - General)'),
  ('exam_rbi_grade_b_depr_dsim','BANKING','RBI_GRADE_B_DEPR_DSIM','RBI Grade B (DEPR / DSIM)'),
  ('exam_rbi_assistant','BANKING','RBI_ASSISTANT','RBI Assistant'),
  ('exam_nabard_grade_a_assistant_manager_rdbs','BANKING','NABARD_GRADE_A_ASSISTANT_MANAGER_RDBS','NABARD Grade A (Assistant Manager - RDBS)'),
  ('exam_nabard_grade_b_manager','BANKING','NABARD_GRADE_B_MANAGER','NABARD Grade B (Manager)'),
  ('exam_lic_aao_assistant_administrative_officer','BANKING','LIC_AAO_ASSISTANT_ADMINISTRATIVE_OFFICER','LIC AAO (Assistant Administrative Officer)'),
  ('exam_lic_ado_apprentice_development_officer','BANKING','LIC_ADO_APPRENTICE_DEVELOPMENT_OFFICER','LIC ADO (Apprentice Development Officer)'),
  ('exam_niacl_ao_new_india_assurance_administrative_officer','BANKING','NIACL_AO_NEW_INDIA_ASSURANCE_ADMINISTRATIVE_OFFICER','NIACL AO (New India Assurance - Administrative Officer)'),
  ('exam_niacl_assistant','BANKING','NIACL_ASSISTANT','NIACL Assistant'),
  ('exam_ap_police_si_civil_apslprb','AP_TS_POLICE','AP_POLICE_SI_CIVIL_APSLPRB','AP Police SI (Civil) - APSLPRB'),
  ('exam_ap_police_si_apsp_rsi_technical_apslprb','AP_TS_POLICE','AP_POLICE_SI_APSP_RSI_TECHNICAL_APSLPRB','AP Police SI (APSP / RSI / Technical) - APSLPRB'),
  ('exam_ap_police_constable_pc_civil_apslprb','AP_TS_POLICE','AP_POLICE_CONSTABLE_PC_CIVIL_APSLPRB','AP Police Constable (PC Civil) - APSLPRB'),
  ('exam_ap_police_constable_apsp_apslprb','AP_TS_POLICE','AP_POLICE_CONSTABLE_APSP_APSLPRB','AP Police Constable (APSP) - APSLPRB'),
  ('exam_tg_ts_police_si_civil_tgprb','AP_TS_POLICE','TG_TS_POLICE_SI_CIVIL_TGPRB','TG/TS Police SI (Civil) - TGPRB'),
  ('exam_tg_ts_police_si_ar_sar_cpl_communications_tgprb','AP_TS_POLICE','TG_TS_POLICE_SI_AR_SAR_CPL_COMMUNICATIONS_TGPRB','TG/TS Police SI (AR / SAR CPL / Communications) - TGPRB'),
  ('exam_tg_ts_police_constable_pc_civil_tgprb','AP_TS_POLICE','TG_TS_POLICE_CONSTABLE_PC_CIVIL_TGPRB','TG/TS Police Constable (PC Civil) - TGPRB'),
  ('exam_tg_ts_police_constable_ar_sar_cpl_tgprb','AP_TS_POLICE','TG_TS_POLICE_CONSTABLE_AR_SAR_CPL_TGPRB','TG/TS Police Constable (AR / SAR CPL) - TGPRB')
ON CONFLICT DO NOTHING;

INSERT INTO "ExamStage" ("id","examId","stageKey","name","order","mode","disposition") VALUES
  ('stage_ssc_cgl_t1','exam_ssc_cgl','SSC_CGL_T1','Tier 1',1,'CBT','CONDUCTED'),
  ('stage_ssc_cgl_t2_p1_s1','exam_ssc_cgl','SSC_CGL_T2_P1_S1','Tier 2 - Paper 1 (Session I: Sec I + Sec II)',2,'CBT','CONDUCTED'),
  ('stage_ssc_cgl_t2_ckt','exam_ssc_cgl','SSC_CGL_T2_CKT','Tier 2 - Paper 1 Sec III Mod I (Computer Knowledge)',3,'CBT','CONDUCTED'),
  ('stage_ssc_cgl_t2_dest','exam_ssc_cgl','SSC_CGL_T2_DEST','Tier 2 - Paper 1 Sec III Mod II (DEST)',4,'SKILL','CATALOG_ONLY'),
  ('stage_ssc_cgl_t2_p2','exam_ssc_cgl','SSC_CGL_T2_P2','Tier 2 - Paper 2 (Statistics / JSO)',5,'CBT','CONDUCTED'),
  ('stage_ssc_cgl_t2_p3','exam_ssc_cgl','SSC_CGL_T2_P3','Tier 2 - Paper 3 (General Studies Fin & Econ / AAO)',6,'CBT','CONDUCTED'),
  ('stage_ssc_chsl_t1','exam_ssc_chsl','SSC_CHSL_T1','Tier 1',1,'CBT','CONDUCTED'),
  ('stage_ssc_chsl_t2_s1','exam_ssc_chsl','SSC_CHSL_T2_S1','Tier 2 - Session I (Sec I + Sec II + CKT)',2,'CBT','CONDUCTED'),
  ('stage_ssc_chsl_t2_skill','exam_ssc_chsl','SSC_CHSL_T2_SKILL','Tier 2 - Session II (Skill / Typing Test)',3,'SKILL','CATALOG_ONLY'),
  ('stage_ssc_mts_s1','exam_ssc_mts_havaldar','SSC_MTS_S1','Session I (Numerical + Reasoning)',1,'CBT','CONDUCTED'),
  ('stage_ssc_mts_s2','exam_ssc_mts_havaldar','SSC_MTS_S2','Session II (GA + English)',2,'CBT','CONDUCTED'),
  ('stage_ssc_mts_pet','exam_ssc_mts_havaldar','SSC_MTS_PET','PET / PST (Havaldar only)',3,'PHYSICAL','CATALOG_ONLY'),
  ('stage_ssc_gd_cbe','exam_ssc_gd_constable','SSC_GD_CBE','Computer Based Examination',1,'CBT','CONDUCTED'),
  ('stage_ssc_gd_pet','exam_ssc_gd_constable','SSC_GD_PET','PET / PST / DME',2,'PHYSICAL','CATALOG_ONLY'),
  ('stage_ssc_cpo_p1','exam_ssc_cpo_si_in_delhi_police_capfs','SSC_CPO_P1','Paper 1',1,'CBT','CONDUCTED'),
  ('stage_ssc_cpo_pet','exam_ssc_cpo_si_in_delhi_police_capfs','SSC_CPO_PET','PET / PST',2,'PHYSICAL','CATALOG_ONLY'),
  ('stage_ssc_cpo_p2','exam_ssc_cpo_si_in_delhi_police_capfs','SSC_CPO_P2','Paper 2 (English Language & Comprehension)',3,'CBT','CONDUCTED'),
  ('stage_ssc_je_p1','exam_ssc_je_junior_engineer','SSC_JE_P1','Paper 1',1,'CBT','CONDUCTED'),
  ('stage_ssc_je_p2','exam_ssc_je_junior_engineer','SSC_JE_P2','Paper 2 (Discipline-specific)',2,'CBT','CONDUCTED'),
  ('stage_ssc_steno_cbt','exam_ssc_stenographer_grade_c_d','SSC_STENO_CBT','Computer Based Test',1,'CBT','CONDUCTED'),
  ('stage_ssc_steno_skill','exam_ssc_stenographer_grade_c_d','SSC_STENO_SKILL','Skill Test (Shorthand)',2,'SKILL','CATALOG_ONLY'),
  ('stage_ssc_sp_matric','exam_ssc_selection_post_phase_exams','SSC_SP_MATRIC','Matriculation Level',1,'CBT','CONDUCTED'),
  ('stage_ssc_sp_hs','exam_ssc_selection_post_phase_exams','SSC_SP_HS','Higher Secondary (10+2) Level',2,'CBT','CONDUCTED'),
  ('stage_ssc_sp_grad','exam_ssc_selection_post_phase_exams','SSC_SP_GRAD','Graduation & Above Level',3,'CBT','CONDUCTED'),
  ('stage_ssc_jht_p1','exam_ssc_jht_junior_hindi_translator','SSC_JHT_P1','Paper 1 (Objective)',1,'CBT','CONDUCTED'),
  ('stage_ssc_jht_p2','exam_ssc_jht_junior_hindi_translator','SSC_JHT_P2','Paper 2 (Descriptive)',2,'DESCRIPTIVE','CATALOG_ONLY'),
  ('stage_rrb_ntpc_g_cbt1','exam_rrb_ntpc_graduate_level','RRB_NTPC_G_CBT1','CBT 1',1,'CBT','CONDUCTED'),
  ('stage_rrb_ntpc_g_cbt2','exam_rrb_ntpc_graduate_level','RRB_NTPC_G_CBT2','CBT 2',2,'CBT','CONDUCTED'),
  ('stage_rrb_ntpc_cbat','exam_rrb_ntpc_graduate_level','RRB_NTPC_CBAT','CBAT (Station Master / Traffic Asst)',3,'PSYCHOMETRIC','CATALOG_ONLY'),
  ('stage_rrb_ntpc_typing','exam_rrb_ntpc_graduate_level','RRB_NTPC_TYPING','Typing Skill Test (CBTST)',4,'SKILL','CATALOG_ONLY'),
  ('stage_rrb_ntpc_u_cbt1','exam_rrb_ntpc_undergraduate_level','RRB_NTPC_U_CBT1','CBT 1',1,'CBT','CONDUCTED'),
  ('stage_rrb_ntpc_u_cbt2','exam_rrb_ntpc_undergraduate_level','RRB_NTPC_U_CBT2','CBT 2',2,'CBT','CONDUCTED'),
  ('stage_rrb_gd_cbt','exam_rrb_group_d_level_1','RRB_GD_CBT','CBT',1,'CBT','CONDUCTED'),
  ('stage_rrb_gd_pet','exam_rrb_group_d_level_1','RRB_GD_PET','PET',2,'PHYSICAL','CATALOG_ONLY'),
  ('stage_rrb_alp_cbt1','exam_rrb_alp_assistant_loco_pilot','RRB_ALP_CBT1','CBT 1',1,'CBT','CONDUCTED'),
  ('stage_rrb_alp_cbt2a','exam_rrb_alp_assistant_loco_pilot','RRB_ALP_CBT2A','CBT 2 - Part A',2,'CBT','CONDUCTED'),
  ('stage_rrb_alp_cbt2b','exam_rrb_alp_assistant_loco_pilot','RRB_ALP_CBT2B','CBT 2 - Part B (Trade)',3,'CBT','CONDUCTED'),
  ('stage_rrb_alp_cbat','exam_rrb_alp_assistant_loco_pilot','RRB_ALP_CBAT','CBAT (Aptitude Test)',4,'PSYCHOMETRIC','CATALOG_ONLY'),
  ('stage_rrb_je_cbt1','exam_rrb_je_junior_engineer','RRB_JE_CBT1','CBT 1',1,'CBT','CONDUCTED'),
  ('stage_rrb_je_cbt2','exam_rrb_je_junior_engineer','RRB_JE_CBT2','CBT 2',2,'CBT','CONDUCTED'),
  ('stage_rrb_rpf_const','exam_rrb_rpf_constable','RRB_RPF_CONST','CBT',1,'CBT','CONDUCTED'),
  ('stage_rrb_rpf_const_pet','exam_rrb_rpf_constable','RRB_RPF_CONST_PET','PET / PMT',2,'PHYSICAL','CATALOG_ONLY'),
  ('stage_rrb_rpf_si','exam_rrb_rpf_si_sub_inspector','RRB_RPF_SI','CBT',1,'CBT','CONDUCTED'),
  ('stage_rrb_rpf_si_pet','exam_rrb_rpf_si_sub_inspector','RRB_RPF_SI_PET','PET / PMT',2,'PHYSICAL','CATALOG_ONLY'),
  ('stage_rrb_tech_g3','exam_rrb_technician','RRB_TECH_G3','Technician Grade III - CBT',1,'CBT','CONDUCTED'),
  ('stage_rrb_tech_g1_cbt1','exam_rrb_technician','RRB_TECH_G1_CBT1','Technician Grade I Signal - CBT 1',2,'CBT','CONDUCTED'),
  ('stage_rrb_tech_g1_cbt2','exam_rrb_technician','RRB_TECH_G1_CBT2','Technician Grade I Signal - CBT 2',3,'CBT','CONDUCTED'),
  ('stage_rrb_mi_cbt','exam_rrb_ministerial_isolated_categories','RRB_MI_CBT','CBT',1,'CBT','CONDUCTED'),
  ('stage_rrb_mi_skill','exam_rrb_ministerial_isolated_categories','RRB_MI_SKILL','Skill / Translation / Steno / Performance Test',2,'SKILL','CATALOG_ONLY'),
  ('stage_rrb_para_cbt','exam_rrb_paramedical_categories','RRB_PARA_CBT','CBT',1,'CBT','CONDUCTED'),
  ('stage_ibps_po_pre','exam_ibps_po_mt','IBPS_PO_PRE','Prelims',1,'CBT','CONDUCTED'),
  ('stage_ibps_po_main_obj','exam_ibps_po_mt','IBPS_PO_MAIN_OBJ','Mains - Objective',2,'CBT','CONDUCTED'),
  ('stage_ibps_po_main_desc','exam_ibps_po_mt','IBPS_PO_MAIN_DESC','Mains - Descriptive (English)',3,'DESCRIPTIVE','CATALOG_ONLY'),
  ('stage_ibps_po_int','exam_ibps_po_mt','IBPS_PO_INT','Interview + Personality Test',4,'INTERVIEW','CATALOG_ONLY'),
  ('stage_ibps_clerk_pre','exam_ibps_clerk_crp_csa','IBPS_CLERK_PRE','Prelims',1,'CBT','CONDUCTED'),
  ('stage_ibps_clerk_main','exam_ibps_clerk_crp_csa','IBPS_CLERK_MAIN','Mains',2,'CBT','CONDUCTED'),
  ('stage_ibps_clerk_lpt','exam_ibps_clerk_crp_csa','IBPS_CLERK_LPT','Local Language Proficiency Test',3,'SKILL','CATALOG_ONLY'),
  ('stage_ibps_so_pre_a','exam_ibps_so_specialist_officer','IBPS_SO_PRE_A','Prelims - IT / AFO / HR / Marketing',1,'CBT','CONDUCTED'),
  ('stage_ibps_so_pre_b','exam_ibps_so_specialist_officer','IBPS_SO_PRE_B','Prelims - Law Officer / Rajbhasha Adhikari',2,'CBT','CONDUCTED'),
  ('stage_ibps_so_main_pk','exam_ibps_so_specialist_officer','IBPS_SO_MAIN_PK','Mains - Professional Knowledge (IT/AFO/Law/HR/Marketing)',3,'CBT','CONDUCTED'),
  ('stage_ibps_so_main_raj','exam_ibps_so_specialist_officer','IBPS_SO_MAIN_RAJ','Mains - Rajbhasha Adhikari (Obj + Desc)',4,'CBT','PARTIAL'),
  ('stage_ibps_rrb_oa_pre','exam_ibps_rrb_crp_rrbs','IBPS_RRB_OA_PRE','Office Assistant - Prelims',1,'CBT','CONDUCTED'),
  ('stage_ibps_rrb_oa_main','exam_ibps_rrb_crp_rrbs','IBPS_RRB_OA_MAIN','Office Assistant - Mains',2,'CBT','CONDUCTED'),
  ('stage_ibps_rrb_s1_pre','exam_ibps_rrb_crp_rrbs','IBPS_RRB_S1_PRE','Officer Scale I - Prelims',3,'CBT','CONDUCTED'),
  ('stage_ibps_rrb_s1_main','exam_ibps_rrb_crp_rrbs','IBPS_RRB_S1_MAIN','Officer Scale I - Mains',4,'CBT','CONDUCTED'),
  ('stage_ibps_rrb_s2_gb','exam_ibps_rrb_crp_rrbs','IBPS_RRB_S2_GB','Officer Scale II - General Banking Officer (Single Exam)',5,'CBT','CONDUCTED'),
  ('stage_ibps_rrb_s2_spl','exam_ibps_rrb_crp_rrbs','IBPS_RRB_S2_SPL','Officer Scale II - Specialist (Single Exam)',6,'CBT','CONDUCTED'),
  ('stage_ibps_rrb_s3','exam_ibps_rrb_crp_rrbs','IBPS_RRB_S3','Officer Scale III (Single Exam)',7,'CBT','CONDUCTED'),
  ('stage_sbi_po_pre','exam_sbi_po_probationary_officer','SBI_PO_PRE','Prelims',1,'CBT','CONDUCTED'),
  ('stage_sbi_po_main_obj','exam_sbi_po_probationary_officer','SBI_PO_MAIN_OBJ','Mains - Objective',2,'CBT','CONDUCTED'),
  ('stage_sbi_po_main_desc','exam_sbi_po_probationary_officer','SBI_PO_MAIN_DESC','Mains - Descriptive (English)',3,'DESCRIPTIVE','CATALOG_ONLY'),
  ('stage_sbi_po_ph3','exam_sbi_po_probationary_officer','SBI_PO_PH3','Phase III (Psychometric + Group Exercise + Interview)',4,'INTERVIEW','CATALOG_ONLY'),
  ('stage_sbi_clerk_pre','exam_sbi_clerk_junior_associate','SBI_CLERK_PRE','Prelims',1,'CBT','CONDUCTED'),
  ('stage_sbi_clerk_main','exam_sbi_clerk_junior_associate','SBI_CLERK_MAIN','Mains',2,'CBT','CONDUCTED'),
  ('stage_sbi_clerk_lpt','exam_sbi_clerk_junior_associate','SBI_CLERK_LPT','Language Proficiency Test',3,'SKILL','CATALOG_ONLY'),
  ('stage_sbi_so_obj','exam_sbi_so_specialist_officer','SBI_SO_OBJ','Objective (Professional Knowledge + General Aptitude)',1,'CBT','CONDUCTED'),
  ('stage_sbi_so_desc','exam_sbi_so_specialist_officer','SBI_SO_DESC','Descriptive (Professional Knowledge, some posts)',2,'DESCRIPTIVE','CATALOG_ONLY'),
  ('stage_rbi_gb_p1','exam_rbi_grade_b_dr_general','RBI_GB_P1','Phase 1 (Prelims)',1,'CBT','CONDUCTED'),
  ('stage_rbi_gb_p2_esi','exam_rbi_grade_b_dr_general','RBI_GB_P2_ESI','Phase 2 - Paper I (Economic & Social Issues)',2,'CBT','PARTIAL'),
  ('stage_rbi_gb_p2_eng','exam_rbi_grade_b_dr_general','RBI_GB_P2_ENG','Phase 2 - Paper II (English Writing Skills)',3,'DESCRIPTIVE','CATALOG_ONLY'),
  ('stage_rbi_gb_p2_fm','exam_rbi_grade_b_dr_general','RBI_GB_P2_FM','Phase 2 - Paper III (Finance & Management)',4,'CBT','PARTIAL'),
  ('stage_rbi_depr_p1','exam_rbi_grade_b_depr_dsim','RBI_DEPR_P1','Phase 1 (Objective - Economics/Statistics)',1,'CBT','CONDUCTED'),
  ('stage_rbi_depr_p2','exam_rbi_grade_b_depr_dsim','RBI_DEPR_P2','Phase 2 (Descriptive + English)',2,'DESCRIPTIVE','CATALOG_ONLY'),
  ('stage_rbi_asst_pre','exam_rbi_assistant','RBI_ASST_PRE','Prelims',1,'CBT','CONDUCTED'),
  ('stage_rbi_asst_main','exam_rbi_assistant','RBI_ASST_MAIN','Mains',2,'CBT','CONDUCTED'),
  ('stage_rbi_asst_lpt','exam_rbi_assistant','RBI_ASST_LPT','Language Proficiency Test',3,'SKILL','CATALOG_ONLY'),
  ('stage_nabard_a_p1','exam_nabard_grade_a_assistant_manager_rdbs','NABARD_A_P1','Phase 1 (Prelims)',1,'CBT','CONDUCTED'),
  ('stage_nabard_a_p2_p1','exam_nabard_grade_a_assistant_manager_rdbs','NABARD_A_P2_P1','Phase 2 - Paper I (General English, Descriptive)',2,'DESCRIPTIVE','CATALOG_ONLY'),
  ('stage_nabard_a_p2_p2','exam_nabard_grade_a_assistant_manager_rdbs','NABARD_A_P2_P2','Phase 2 - Paper II (ESI & ARD / Stream Paper)',3,'CBT','PARTIAL'),
  ('stage_nabard_b_p1','exam_nabard_grade_b_manager','NABARD_B_P1','Phase 1 (Prelims)',1,'CBT','CONDUCTED'),
  ('stage_nabard_b_p2','exam_nabard_grade_b_manager','NABARD_B_P2','Phase 2 (Descriptive Papers)',2,'DESCRIPTIVE','CATALOG_ONLY'),
  ('stage_lic_aao_pre','exam_lic_aao_assistant_administrative_officer','LIC_AAO_PRE','Prelims',1,'CBT','CONDUCTED'),
  ('stage_lic_aao_main','exam_lic_aao_assistant_administrative_officer','LIC_AAO_MAIN','Mains',2,'CBT','CONDUCTED'),
  ('stage_lic_ado_pre','exam_lic_ado_apprentice_development_officer','LIC_ADO_PRE','Prelims',1,'CBT','CONDUCTED'),
  ('stage_lic_ado_main','exam_lic_ado_apprentice_development_officer','LIC_ADO_MAIN','Mains',2,'CBT','CONDUCTED'),
  ('stage_niacl_ao_pre','exam_niacl_ao_new_india_assurance_administrative_officer','NIACL_AO_PRE','Prelims',1,'CBT','CONDUCTED'),
  ('stage_niacl_ao_main','exam_niacl_ao_new_india_assurance_administrative_officer','NIACL_AO_MAIN','Mains',2,'CBT','CONDUCTED'),
  ('stage_niacl_asst_pre','exam_niacl_assistant','NIACL_ASST_PRE','Prelims',1,'CBT','CONDUCTED'),
  ('stage_niacl_asst_main','exam_niacl_assistant','NIACL_ASST_MAIN','Mains',2,'CBT','CONDUCTED'),
  ('stage_ap_si_pre_p1','exam_ap_police_si_civil_apslprb','AP_SI_PRE_P1','Preliminary Written Test - Paper I (Arithmetic & Reasoning)',1,'OMR','CONDUCTED'),
  ('stage_ap_si_pre_p2','exam_ap_police_si_civil_apslprb','AP_SI_PRE_P2','Preliminary Written Test - Paper II (General Studies)',2,'OMR','CONDUCTED'),
  ('stage_ap_si_pmt','exam_ap_police_si_civil_apslprb','AP_SI_PMT','PMT / PET',3,'PHYSICAL','CATALOG_ONLY'),
  ('stage_ap_si_fwe_p1','exam_ap_police_si_civil_apslprb','AP_SI_FWE_P1','Final Written - Paper I (English, Degree standard)',4,'DESCRIPTIVE','CATALOG_ONLY'),
  ('stage_ap_si_fwe_p2','exam_ap_police_si_civil_apslprb','AP_SI_FWE_P2','Final Written - Paper II (Telugu or Urdu, Degree standard)',5,'DESCRIPTIVE','CATALOG_ONLY'),
  ('stage_ap_si_fwe_p3','exam_ap_police_si_civil_apslprb','AP_SI_FWE_P3','Final Written - Paper III (Arithmetic & Reasoning/Mental Ability)',6,'OMR','CONDUCTED'),
  ('stage_ap_si_fwe_p4','exam_ap_police_si_civil_apslprb','AP_SI_FWE_P4','Final Written - Paper IV (General Studies)',7,'OMR','CONDUCTED'),
  ('stage_ap_si_apsp_fwe','exam_ap_police_si_apsp_rsi_technical_apslprb','AP_SI_APSP_FWE','Final Written (Papers III & IV, 100 marks each)',1,'OMR','CONDUCTED'),
  ('stage_ap_pc_pre','exam_ap_police_constable_pc_civil_apslprb','AP_PC_PRE','Preliminary Written Test',1,'OMR','CONDUCTED'),
  ('stage_ap_pc_pmt','exam_ap_police_constable_pc_civil_apslprb','AP_PC_PMT','PMT / PET',2,'PHYSICAL','CATALOG_ONLY'),
  ('stage_ap_pc_fwe','exam_ap_police_constable_pc_civil_apslprb','AP_PC_FWE','Final Written Examination',3,'OMR','CONDUCTED'),
  ('stage_ap_pc_apsp_fwe','exam_ap_police_constable_apsp_apslprb','AP_PC_APSP_FWE','Final Written Examination',1,'OMR','CONDUCTED'),
  ('stage_ts_si_pre','exam_tg_ts_police_si_civil_tgprb','TS_SI_PRE','Preliminary Written Test',1,'OMR','CONDUCTED'),
  ('stage_ts_si_pmt','exam_tg_ts_police_si_civil_tgprb','TS_SI_PMT','PMT / PET',2,'PHYSICAL','CATALOG_ONLY'),
  ('stage_ts_si_fwe_p1','exam_tg_ts_police_si_civil_tgprb','TS_SI_FWE_P1','Final Written - Paper I (English)',3,'OMR','PARTIAL'),
  ('stage_ts_si_fwe_p2','exam_tg_ts_police_si_civil_tgprb','TS_SI_FWE_P2','Final Written - Paper II (Telugu or Urdu)',4,'OMR','PARTIAL'),
  ('stage_ts_si_fwe_p3','exam_tg_ts_police_si_civil_tgprb','TS_SI_FWE_P3','Final Written - Paper III (Arithmetic & Reasoning/Mental Ability)',5,'OMR','CONDUCTED'),
  ('stage_ts_si_fwe_p4','exam_tg_ts_police_si_civil_tgprb','TS_SI_FWE_P4','Final Written - Paper IV (General Studies incl. Telangana Movement & State Formation)',6,'OMR','CONDUCTED'),
  ('stage_ts_si_ar_fwe','exam_tg_ts_police_si_ar_sar_cpl_communications_tgprb','TS_SI_AR_FWE','Final Written (variant pattern)',1,'OMR','CONDUCTED'),
  ('stage_ts_pc_pre','exam_tg_ts_police_constable_pc_civil_tgprb','TS_PC_PRE','Preliminary Written Test',1,'OMR','CONDUCTED'),
  ('stage_ts_pc_pet','exam_tg_ts_police_constable_pc_civil_tgprb','TS_PC_PET','PMT / PET',2,'PHYSICAL','CATALOG_ONLY'),
  ('stage_ts_pc_fwe','exam_tg_ts_police_constable_pc_civil_tgprb','TS_PC_FWE','Final Written Examination',3,'OMR','CONDUCTED'),
  ('stage_ts_pc_ar_fwe','exam_tg_ts_police_constable_ar_sar_cpl_tgprb','TS_PC_AR_FWE','Final Written Examination (variant)',1,'OMR','CONDUCTED')
ON CONFLICT DO NOTHING;

-- SSC CGL Tier 1 is configured in seed.sql, which its tests pin; declaring it again here
-- inserted a config the primary key skipped and four sections the (baseConfigId, order) partial
-- unique swallowed, so the catalog silently did nothing for the one exam both files describe.
INSERT INTO "BaseConfig" ("id","examStageId","name","isDefault","version","totalQuestions","totalMarks","durationSec","timerTemplate","navigation","defaultTestUi","languageMode","languages","shuffleQuestions","shuffleOptions","calculatorEnabled","scoringVersion") VALUES
  ('config_ssc_cgl_t2_p1_s1','stage_ssc_cgl_t2_p1_s1','SSC CGL — Tier 2 - Paper 1 (Session I: Sec I + Sec II) (official pattern)',true,1,130,390.00,7200,'COMPOSITE_FREE','FREE','CBT','DUAL',ARRAY['EN','HI']::"SupportedLanguage"[],true,true,false,1),
  ('config_ssc_cgl_t2_ckt','stage_ssc_cgl_t2_ckt','SSC CGL — Tier 2 - Paper 1 Sec III Mod I (Computer Knowledge) (official pattern)',true,1,20,60.00,900,'COMPOSITE_FREE','FREE','CBT','DUAL',ARRAY['EN','HI']::"SupportedLanguage"[],true,true,false,1),
  ('config_ssc_chsl_t1','stage_ssc_chsl_t1','SSC CHSL — Tier 1 (official pattern)',true,1,100,200.00,3600,'COMPOSITE_FREE','FREE','CBT','DUAL',ARRAY['EN','HI']::"SupportedLanguage"[],true,true,false,1),
  ('config_ssc_mts_s1','stage_ssc_mts_s1','SSC MTS & Havaldar — Session I (Numerical + Reasoning) (official pattern)',true,1,40,120.00,2700,'COMPOSITE_FREE','FREE','CBT','DUAL',ARRAY['EN','HI']::"SupportedLanguage"[],true,true,false,1),
  ('config_ssc_mts_s2','stage_ssc_mts_s2','SSC MTS & Havaldar — Session II (GA + English) (official pattern)',true,1,50,150.00,2700,'COMPOSITE_FREE','FREE','CBT','DUAL',ARRAY['EN','HI']::"SupportedLanguage"[],true,true,false,1),
  ('config_ssc_gd_cbe','stage_ssc_gd_cbe','SSC GD Constable — Computer Based Examination (official pattern)',true,1,80,160.00,3600,'COMPOSITE_FREE','FREE','CBT','DUAL',ARRAY['EN','HI']::"SupportedLanguage"[],true,true,false,1),
  ('config_ssc_cpo_p1','stage_ssc_cpo_p1','SSC CPO (SI in Delhi Police & CAPFs) — Paper 1 (official pattern)',true,1,200,200.00,7200,'SECTIONAL_LOCKED','FREE','CBT','DUAL',ARRAY['EN','HI']::"SupportedLanguage"[],true,true,false,1),
  ('config_ssc_je_p1','stage_ssc_je_p1','SSC JE (Junior Engineer) — Paper 1 (official pattern)',true,1,200,200.00,7200,'COMPOSITE_FREE','FREE','CBT','DUAL',ARRAY['EN','HI']::"SupportedLanguage"[],true,true,false,1),
  ('config_ssc_steno_cbt','stage_ssc_steno_cbt','SSC Stenographer (Grade C & D) — Computer Based Test (official pattern)',true,1,200,200.00,7200,'COMPOSITE_FREE','FREE','CBT','DUAL',ARRAY['EN','HI']::"SupportedLanguage"[],true,true,false,1),
  ('config_rrb_ntpc_g_cbt1','stage_rrb_ntpc_g_cbt1','RRB NTPC (Graduate Level) — CBT 1 (official pattern)',true,1,100,100.00,5400,'COMPOSITE_FREE','FREE','CBT','SINGLE',ARRAY['EN','HI','TE']::"SupportedLanguage"[],true,true,false,1),
  ('config_rrb_ntpc_g_cbt2','stage_rrb_ntpc_g_cbt2','RRB NTPC (Graduate Level) — CBT 2 (official pattern)',true,1,120,120.00,5400,'COMPOSITE_FREE','FREE','CBT','SINGLE',ARRAY['EN','HI','TE']::"SupportedLanguage"[],true,true,false,1),
  ('config_rrb_gd_cbt','stage_rrb_gd_cbt','RRB Group D (Level 1) — CBT (official pattern)',true,1,100,100.00,5400,'COMPOSITE_FREE','FREE','CBT','SINGLE',ARRAY['EN','HI','TE']::"SupportedLanguage"[],true,true,false,1),
  ('config_rrb_alp_cbt2a','stage_rrb_alp_cbt2a','RRB ALP (Assistant Loco Pilot) — CBT 2 - Part A (official pattern)',true,1,100,100.00,5400,'COMPOSITE_FREE','FREE','CBT','SINGLE',ARRAY['EN','HI','TE']::"SupportedLanguage"[],true,true,false,1),
  ('config_rrb_alp_cbt2b','stage_rrb_alp_cbt2b','RRB ALP (Assistant Loco Pilot) — CBT 2 - Part B (Trade) (official pattern)',true,1,75,75.00,3600,'COMPOSITE_FREE','FREE','CBT','SINGLE',ARRAY['EN','HI','TE']::"SupportedLanguage"[],true,true,false,1),
  ('config_rrb_je_cbt2','stage_rrb_je_cbt2','RRB JE (Junior Engineer) — CBT 2 (official pattern)',true,1,150,150.00,7200,'COMPOSITE_FREE','FREE','CBT','SINGLE',ARRAY['EN','HI','TE']::"SupportedLanguage"[],true,true,true,1),
  ('config_rrb_rpf_const','stage_rrb_rpf_const','RRB RPF Constable — CBT (official pattern)',true,1,120,120.00,5400,'COMPOSITE_FREE','FREE','CBT','SINGLE',ARRAY['EN','HI','TE']::"SupportedLanguage"[],true,true,false,1),
  ('config_ibps_po_pre','stage_ibps_po_pre','IBPS PO / MT — Prelims (official pattern)',true,1,100,100.00,3600,'SECTIONAL_LOCKED','FREE','CBT','SINGLE',ARRAY['EN','HI']::"SupportedLanguage"[],true,true,false,1),
  ('config_ibps_po_main_obj','stage_ibps_po_main_obj','IBPS PO / MT — Mains - Objective (official pattern)',true,1,170,199.70,10800,'SECTIONAL_LOCKED','FREE','CBT','SINGLE',ARRAY['EN','HI']::"SupportedLanguage"[],true,true,false,1),
  ('config_ibps_clerk_pre','stage_ibps_clerk_pre','IBPS Clerk (CRP CSA) — Prelims (official pattern)',true,1,100,100.00,3600,'SECTIONAL_LOCKED','FREE','CBT','SINGLE',ARRAY['EN','HI','TE']::"SupportedLanguage"[],true,true,false,1),
  ('config_ibps_clerk_main','stage_ibps_clerk_main','IBPS Clerk (CRP CSA) — Mains (official pattern)',true,1,155,200.05,9600,'SECTIONAL_LOCKED','FREE','CBT','SINGLE',ARRAY['EN','HI','TE']::"SupportedLanguage"[],true,true,false,1),
  ('config_ibps_rrb_oa_pre','stage_ibps_rrb_oa_pre','IBPS RRB (CRP RRBs) — Office Assistant - Prelims (official pattern)',true,1,80,80.00,2700,'COMPOSITE_FREE','FREE','CBT','SINGLE',ARRAY['EN','HI','TE']::"SupportedLanguage"[],true,true,false,1),
  ('config_ibps_rrb_oa_main','stage_ibps_rrb_oa_main','IBPS RRB (CRP RRBs) — Office Assistant - Mains (official pattern)',true,1,200,200.00,7200,'COMPOSITE_FREE','FREE','CBT','SINGLE',ARRAY['EN','HI','TE']::"SupportedLanguage"[],true,true,false,1),
  ('config_sbi_clerk_main','stage_sbi_clerk_main','SBI Clerk (Junior Associate) — Mains (official pattern)',true,1,190,200.00,9600,'SECTIONAL_LOCKED','FREE','CBT','SINGLE',ARRAY['EN','HI','TE']::"SupportedLanguage"[],true,true,false,1),
  ('config_rbi_gb_p1','stage_rbi_gb_p1','RBI Grade B (DR - General) — Phase 1 (Prelims) (official pattern)',true,1,200,200.00,7200,'SECTIONAL_LOCKED','FREE','CBT','SINGLE',ARRAY['EN','HI']::"SupportedLanguage"[],true,true,false,1),
  ('config_ap_si_fwe_p3','stage_ap_si_fwe_p3','AP Police SI (Civil) - APSLPRB — Final Written - Paper III (Arithmetic & Reasoning/Mental Ability) (official pattern)',true,1,200,200.00,10800,'COMPOSITE_FREE','FREE','OMR','SINGLE',ARRAY['EN','TE']::"SupportedLanguage"[],true,true,false,1),
  ('config_ap_si_fwe_p4','stage_ap_si_fwe_p4','AP Police SI (Civil) - APSLPRB — Final Written - Paper IV (General Studies) (official pattern)',true,1,200,200.00,10800,'COMPOSITE_FREE','FREE','OMR','SINGLE',ARRAY['EN','TE']::"SupportedLanguage"[],true,true,false,1),
  ('config_ts_si_pre','stage_ts_si_pre','TG/TS Police SI (Civil) - TGPRB — Preliminary Written Test (official pattern)',true,1,200,200.00,10800,'COMPOSITE_FREE','FREE','OMR','SINGLE',ARRAY['EN','TE']::"SupportedLanguage"[],true,true,false,1),
  ('config_ts_si_fwe_p3','stage_ts_si_fwe_p3','TG/TS Police SI (Civil) - TGPRB — Final Written - Paper III (Arithmetic & Reasoning/Mental Ability) (official pattern)',true,1,200,200.00,10800,'COMPOSITE_FREE','FREE','OMR','SINGLE',ARRAY['EN','TE']::"SupportedLanguage"[],true,true,false,1),
  ('config_ts_si_fwe_p4','stage_ts_si_fwe_p4','TG/TS Police SI (Civil) - TGPRB — Final Written - Paper IV (General Studies incl. Telangana Movement & State Formation) (official pattern)',true,1,200,200.00,10800,'COMPOSITE_FREE','FREE','OMR','SINGLE',ARRAY['EN','TE']::"SupportedLanguage"[],true,true,false,1)
ON CONFLICT DO NOTHING;

INSERT INTO "BaseConfigSection" ("id","baseConfigId","name","order","subjectId","questionCount","marksPerQuestion","negativeMarks","durationSec","mandatory","meritOrQualifying","difficultyMix") VALUES
  ('section_ssc_cgl_t2_p1_s1_1','config_ssc_cgl_t2_p1_s1','Section I Module I: Mathematical Abilities',1,'subject_quantitative',30,3.00,1.00,NULL,true,'MERIT','{"indicative": "Moderate-Difficult"}'::jsonb),
  ('section_ssc_cgl_t2_p1_s1_2','config_ssc_cgl_t2_p1_s1','Section I Module II: Reasoning & General Intelligence',2,'subject_reasoning',30,3.00,1.00,NULL,true,'MERIT','{"indicative": "Moderate"}'::jsonb),
  ('section_ssc_cgl_t2_p1_s1_3','config_ssc_cgl_t2_p1_s1','Section II Module I: English Language & Comprehension',3,'subject_english',45,3.00,1.00,NULL,true,'MERIT','{"indicative": "Moderate"}'::jsonb),
  ('section_ssc_cgl_t2_p1_s1_4','config_ssc_cgl_t2_p1_s1','Section II Module II: General Awareness',4,'subject_gk',25,3.00,1.00,NULL,true,'MERIT','{"indicative": "Moderate"}'::jsonb),
  ('section_ssc_cgl_t2_ckt_1','config_ssc_cgl_t2_ckt','Computer Knowledge Module',1,'subject_computer',20,3.00,1.00,NULL,true,'QUALIFYING','{"indicative": "Easy"}'::jsonb),
  ('section_ssc_chsl_t1_1','config_ssc_chsl_t1','General Intelligence',1,'subject_reasoning',25,2.00,0.50,NULL,true,'MERIT','{"indicative": "Easy-Moderate"}'::jsonb),
  ('section_ssc_chsl_t1_2','config_ssc_chsl_t1','General Awareness',2,'subject_gk',25,2.00,0.50,NULL,true,'MERIT','{"indicative": "Moderate"}'::jsonb),
  ('section_ssc_chsl_t1_3','config_ssc_chsl_t1','Quantitative Aptitude',3,'subject_quantitative',25,2.00,0.50,NULL,true,'MERIT','{"indicative": "Easy-Moderate"}'::jsonb),
  ('section_ssc_chsl_t1_4','config_ssc_chsl_t1','English Language',4,'subject_english',25,2.00,0.50,NULL,true,'MERIT','{"indicative": "Easy"}'::jsonb),
  ('section_ssc_mts_s1_1','config_ssc_mts_s1','Numerical & Mathematical Ability',1,'subject_quantitative',20,3.00,0.00,NULL,true,'MERIT','{"indicative": "Easy"}'::jsonb),
  ('section_ssc_mts_s1_2','config_ssc_mts_s1','Reasoning Ability & Problem Solving',2,'subject_reasoning',20,3.00,0.00,NULL,true,'MERIT','{"indicative": "Easy"}'::jsonb),
  ('section_ssc_mts_s2_1','config_ssc_mts_s2','General Awareness',1,'subject_gk',25,3.00,1.00,NULL,true,'MERIT','{"indicative": "Moderate"}'::jsonb),
  ('section_ssc_mts_s2_2','config_ssc_mts_s2','English Language & Comprehension',2,'subject_english',25,3.00,1.00,NULL,true,'MERIT','{"indicative": "Easy"}'::jsonb),
  ('section_ssc_gd_cbe_1','config_ssc_gd_cbe','General Intelligence & Reasoning',1,'subject_reasoning',20,2.00,0.25,NULL,true,'MERIT','{"indicative": "Easy"}'::jsonb),
  ('section_ssc_gd_cbe_2','config_ssc_gd_cbe','General Knowledge & General Awareness',2,'subject_gk',20,2.00,0.25,NULL,true,'MERIT','{"indicative": "Easy-Moderate"}'::jsonb),
  ('section_ssc_gd_cbe_3','config_ssc_gd_cbe','Elementary Mathematics',3,'subject_quantitative',20,2.00,0.25,NULL,true,'MERIT','{"indicative": "Easy"}'::jsonb),
  ('section_ssc_gd_cbe_4','config_ssc_gd_cbe','English / Hindi',4,'subject_english',20,2.00,0.25,NULL,true,'MERIT','{"indicative": "Easy"}'::jsonb),
  ('section_ssc_cpo_p1_1','config_ssc_cpo_p1','General Intelligence & Reasoning',1,'subject_reasoning',50,1.00,0.25,1800,true,'MERIT','{"indicative": "Easy-Moderate"}'::jsonb),
  ('section_ssc_cpo_p1_2','config_ssc_cpo_p1','General Knowledge & General Awareness',2,'subject_gk',50,1.00,0.25,1800,true,'MERIT','{"indicative": "Moderate"}'::jsonb),
  ('section_ssc_cpo_p1_3','config_ssc_cpo_p1','Quantitative Aptitude',3,'subject_quantitative',50,1.00,0.25,1800,true,'MERIT','{"indicative": "Moderate"}'::jsonb),
  ('section_ssc_cpo_p1_4','config_ssc_cpo_p1','English Comprehension',4,'subject_english',50,1.00,0.25,1800,true,'MERIT','{"indicative": "Easy-Moderate"}'::jsonb),
  ('section_ssc_je_p1_1','config_ssc_je_p1','General Intelligence & Reasoning',1,'subject_reasoning',50,1.00,0.25,NULL,true,'MERIT','{"indicative": "Easy-Moderate"}'::jsonb),
  ('section_ssc_je_p1_2','config_ssc_je_p1','General Awareness',2,'subject_gk',50,1.00,0.25,NULL,true,'MERIT','{"indicative": "Moderate"}'::jsonb),
  ('section_ssc_je_p1_3','config_ssc_je_p1','General Engineering (Civil / Electrical / Mechanical - choose one)',3,'subject_science',100,1.00,0.25,NULL,true,'MERIT','{"indicative": "Moderate-Difficult"}'::jsonb),
  ('section_ssc_steno_cbt_1','config_ssc_steno_cbt','General Intelligence & Reasoning',1,'subject_reasoning',50,1.00,0.25,NULL,true,'MERIT','{"indicative": "Easy-Moderate"}'::jsonb),
  ('section_ssc_steno_cbt_2','config_ssc_steno_cbt','General Awareness',2,'subject_gk',50,1.00,0.25,NULL,true,'MERIT','{"indicative": "Moderate"}'::jsonb),
  ('section_ssc_steno_cbt_3','config_ssc_steno_cbt','English Language & Comprehension',3,'subject_english',100,1.00,0.25,NULL,true,'MERIT','{"indicative": "Moderate"}'::jsonb),
  ('section_rrb_ntpc_g_cbt1_1','config_rrb_ntpc_g_cbt1','General Awareness',1,'subject_gk',40,1.00,0.33,NULL,true,'QUALIFYING','{"indicative": "Moderate"}'::jsonb),
  ('section_rrb_ntpc_g_cbt1_2','config_rrb_ntpc_g_cbt1','Mathematics',2,'subject_quantitative',30,1.00,0.33,NULL,true,'QUALIFYING','{"indicative": "Easy-Moderate"}'::jsonb),
  ('section_rrb_ntpc_g_cbt1_3','config_rrb_ntpc_g_cbt1','General Intelligence & Reasoning',3,'subject_reasoning',30,1.00,0.33,NULL,true,'QUALIFYING','{"indicative": "Easy-Moderate"}'::jsonb),
  ('section_rrb_ntpc_g_cbt2_1','config_rrb_ntpc_g_cbt2','General Awareness',1,'subject_gk',50,1.00,0.33,NULL,true,'MERIT','{"indicative": "Moderate"}'::jsonb),
  ('section_rrb_ntpc_g_cbt2_2','config_rrb_ntpc_g_cbt2','Mathematics',2,'subject_quantitative',35,1.00,0.33,NULL,true,'MERIT','{"indicative": "Moderate"}'::jsonb),
  ('section_rrb_ntpc_g_cbt2_3','config_rrb_ntpc_g_cbt2','General Intelligence & Reasoning',3,'subject_reasoning',35,1.00,0.33,NULL,true,'MERIT','{"indicative": "Moderate"}'::jsonb),
  ('section_rrb_gd_cbt_1','config_rrb_gd_cbt','General Science',1,'subject_science',25,1.00,0.33,NULL,true,'MERIT','{"indicative": "Easy-Moderate"}'::jsonb),
  ('section_rrb_gd_cbt_2','config_rrb_gd_cbt','Mathematics',2,'subject_quantitative',25,1.00,0.33,NULL,true,'MERIT','{"indicative": "Easy"}'::jsonb),
  ('section_rrb_gd_cbt_3','config_rrb_gd_cbt','General Intelligence & Reasoning',3,'subject_reasoning',30,1.00,0.33,NULL,true,'MERIT','{"indicative": "Easy-Moderate"}'::jsonb),
  ('section_rrb_gd_cbt_4','config_rrb_gd_cbt','General Awareness & Current Affairs',4,'subject_gk',20,1.00,0.33,NULL,true,'MERIT','{"indicative": "Moderate"}'::jsonb),
  ('section_rrb_alp_cbt2a_1','config_rrb_alp_cbt2a','Mathematics',1,'subject_quantitative',25,1.00,0.33,NULL,true,'MERIT','{"indicative": "Moderate"}'::jsonb),
  ('section_rrb_alp_cbt2a_2','config_rrb_alp_cbt2a','General Intelligence & Reasoning',2,'subject_reasoning',25,1.00,0.33,NULL,true,'MERIT','{"indicative": "Moderate"}'::jsonb),
  ('section_rrb_alp_cbt2a_3','config_rrb_alp_cbt2a','Basic Science & Engineering',3,'subject_science',40,1.00,0.33,NULL,true,'MERIT','{"indicative": "Moderate-Difficult"}'::jsonb),
  ('section_rrb_alp_cbt2a_4','config_rrb_alp_cbt2a','General Awareness & Current Affairs',4,'subject_gk',10,1.00,0.33,NULL,true,'MERIT','{"indicative": "Moderate"}'::jsonb),
  ('section_rrb_alp_cbt2b_1','config_rrb_alp_cbt2b','Relevant Trade (qualifying)',1,'subject_gk',75,1.00,0.33,NULL,true,'QUALIFYING','{"indicative": "Moderate"}'::jsonb),
  ('section_rrb_je_cbt2_1','config_rrb_je_cbt2','General Awareness',1,'subject_gk',15,1.00,0.33,NULL,true,'MERIT','{"indicative": "Moderate"}'::jsonb),
  ('section_rrb_je_cbt2_2','config_rrb_je_cbt2','Physics & Chemistry',2,'subject_science',15,1.00,0.33,NULL,true,'MERIT','{"indicative": "Moderate"}'::jsonb),
  ('section_rrb_je_cbt2_3','config_rrb_je_cbt2','Basics of Computers & Applications',3,'subject_computer',10,1.00,0.33,NULL,true,'MERIT','{"indicative": "Easy"}'::jsonb),
  ('section_rrb_je_cbt2_4','config_rrb_je_cbt2','Basics of Environment & Pollution Control',4,'subject_gk',10,1.00,0.33,NULL,true,'MERIT','{"indicative": "Easy"}'::jsonb),
  ('section_rrb_je_cbt2_5','config_rrb_je_cbt2','Technical Abilities',5,'subject_gk',100,1.00,0.33,NULL,true,'MERIT','{"indicative": "Difficult"}'::jsonb),
  ('section_rrb_rpf_const_1','config_rrb_rpf_const','General Awareness',1,'subject_gk',50,1.00,0.33,NULL,true,'MERIT','{"indicative": "Moderate"}'::jsonb),
  ('section_rrb_rpf_const_2','config_rrb_rpf_const','Arithmetic',2,'subject_quantitative',35,1.00,0.33,NULL,true,'MERIT','{"indicative": "Easy-Moderate"}'::jsonb),
  ('section_rrb_rpf_const_3','config_rrb_rpf_const','General Intelligence & Reasoning',3,'subject_reasoning',35,1.00,0.33,NULL,true,'MERIT','{"indicative": "Easy-Moderate"}'::jsonb),
  ('section_ibps_po_pre_1','config_ibps_po_pre','English Language',1,'subject_english',30,1.00,0.25,1200,true,'QUALIFYING','{"indicative": "Moderate"}'::jsonb),
  ('section_ibps_po_pre_2','config_ibps_po_pre','Quantitative Aptitude',2,'subject_quantitative',35,1.00,0.25,1200,true,'QUALIFYING','{"indicative": "Moderate"}'::jsonb),
  ('section_ibps_po_pre_3','config_ibps_po_pre','Reasoning Ability',3,'subject_reasoning',35,1.00,0.25,1200,true,'QUALIFYING','{"indicative": "Moderate-Difficult"}'::jsonb),
  ('section_ibps_po_main_obj_1','config_ibps_po_main_obj','Reasoning & Computer Aptitude',1,'subject_reasoning',45,1.33,0.25,3600,true,'MERIT','{"indicative": "Difficult"}'::jsonb),
  ('section_ibps_po_main_obj_2','config_ibps_po_main_obj','Data Analysis & Interpretation',2,'subject_quantitative',35,1.71,0.25,2700,true,'MERIT','{"indicative": "Difficult"}'::jsonb),
  ('section_ibps_po_main_obj_3','config_ibps_po_main_obj','General / Economy / Banking Awareness',3,'subject_gk',50,1.20,0.25,2100,true,'MERIT','{"indicative": "Moderate"}'::jsonb),
  ('section_ibps_po_main_obj_4','config_ibps_po_main_obj','English Language',4,'subject_english',40,0.50,0.25,2400,true,'MERIT','{"indicative": "Moderate-Difficult"}'::jsonb),
  ('section_ibps_clerk_pre_1','config_ibps_clerk_pre','English Language',1,'subject_english',30,1.00,0.25,1200,true,'QUALIFYING','{"indicative": "Easy-Moderate"}'::jsonb),
  ('section_ibps_clerk_pre_2','config_ibps_clerk_pre','Numerical Ability',2,'subject_quantitative',35,1.00,0.25,1200,true,'QUALIFYING','{"indicative": "Easy-Moderate"}'::jsonb),
  ('section_ibps_clerk_pre_3','config_ibps_clerk_pre','Reasoning Ability',3,'subject_reasoning',35,1.00,0.25,1200,true,'QUALIFYING','{"indicative": "Easy-Moderate"}'::jsonb),
  ('section_ibps_clerk_main_1','config_ibps_clerk_main','General / Financial Awareness',1,'subject_gk',40,1.25,0.25,2100,true,'MERIT','{"indicative": "Moderate"}'::jsonb),
  ('section_ibps_clerk_main_2','config_ibps_clerk_main','General English',2,'subject_english',40,1.00,0.25,2100,true,'MERIT','{"indicative": "Moderate"}'::jsonb),
  ('section_ibps_clerk_main_3','config_ibps_clerk_main','Reasoning Ability & Computer Aptitude',3,'subject_reasoning',40,1.50,0.25,2700,true,'MERIT','{"indicative": "Moderate-Difficult"}'::jsonb),
  ('section_ibps_clerk_main_4','config_ibps_clerk_main','Quantitative Aptitude',4,'subject_quantitative',35,1.43,0.25,2700,true,'MERIT','{"indicative": "Moderate-Difficult"}'::jsonb),
  ('section_ibps_rrb_oa_pre_1','config_ibps_rrb_oa_pre','Reasoning',1,'subject_reasoning',40,1.00,0.25,NULL,true,'QUALIFYING','{"indicative": "Easy-Moderate"}'::jsonb),
  ('section_ibps_rrb_oa_pre_2','config_ibps_rrb_oa_pre','Numerical Ability',2,'subject_quantitative',40,1.00,0.25,NULL,true,'QUALIFYING','{"indicative": "Easy-Moderate"}'::jsonb),
  ('section_ibps_rrb_oa_main_1','config_ibps_rrb_oa_main','Reasoning',1,'subject_reasoning',40,1.00,0.25,NULL,true,'MERIT','{"indicative": "Moderate"}'::jsonb),
  ('section_ibps_rrb_oa_main_2','config_ibps_rrb_oa_main','Numerical Ability',2,'subject_quantitative',40,1.00,0.25,NULL,true,'MERIT','{"indicative": "Moderate"}'::jsonb),
  ('section_ibps_rrb_oa_main_3','config_ibps_rrb_oa_main','General Awareness',3,'subject_gk',40,1.00,0.25,NULL,true,'MERIT','{"indicative": "Moderate"}'::jsonb),
  ('section_ibps_rrb_oa_main_4','config_ibps_rrb_oa_main','English OR Hindi Language (candidate chooses one)',4,'subject_english',40,1.00,0.25,NULL,true,'MERIT','{"indicative": "Moderate"}'::jsonb),
  ('section_ibps_rrb_oa_main_5','config_ibps_rrb_oa_main','Computer Knowledge',5,'subject_computer',40,1.00,0.25,NULL,true,'MERIT','{"indicative": "Easy"}'::jsonb),
  ('section_sbi_clerk_main_1','config_sbi_clerk_main','General / Financial Awareness',1,'subject_gk',50,1.00,0.25,2100,true,'MERIT','{"indicative": "Moderate"}'::jsonb),
  ('section_sbi_clerk_main_2','config_sbi_clerk_main','General English',2,'subject_english',40,1.00,0.25,2100,true,'MERIT','{"indicative": "Moderate"}'::jsonb),
  ('section_sbi_clerk_main_3','config_sbi_clerk_main','Quantitative Aptitude',3,'subject_quantitative',50,1.00,0.25,2700,true,'MERIT','{"indicative": "Moderate-Difficult"}'::jsonb),
  ('section_sbi_clerk_main_4','config_sbi_clerk_main','Reasoning Ability & Computer Aptitude',4,'subject_reasoning',50,1.20,0.25,2700,true,'MERIT','{"indicative": "Difficult"}'::jsonb),
  ('section_rbi_gb_p1_1','config_rbi_gb_p1','General Awareness',1,'subject_gk',80,1.00,0.25,1500,true,'QUALIFYING','{"indicative": "Difficult"}'::jsonb),
  ('section_rbi_gb_p1_2','config_rbi_gb_p1','Reasoning',2,'subject_reasoning',60,1.00,0.25,2700,true,'QUALIFYING','{"indicative": "Difficult"}'::jsonb),
  ('section_rbi_gb_p1_3','config_rbi_gb_p1','English Language',3,'subject_english',30,1.00,0.25,1500,true,'QUALIFYING','{"indicative": "Moderate-Difficult"}'::jsonb),
  ('section_rbi_gb_p1_4','config_rbi_gb_p1','Quantitative Aptitude',4,'subject_quantitative',30,1.00,0.25,1500,true,'QUALIFYING','{"indicative": "Difficult"}'::jsonb),
  ('section_ap_si_fwe_p3_1','config_ap_si_fwe_p3','Arithmetic (SSC standard)',1,'subject_quantitative',100,1.00,0.00,NULL,true,'MERIT','{"indicative": "Moderate"}'::jsonb),
  ('section_ap_si_fwe_p3_2','config_ap_si_fwe_p3','Test of Reasoning / Mental Ability',2,'subject_reasoning',100,1.00,0.00,NULL,true,'MERIT','{"indicative": "Moderate"}'::jsonb),
  ('section_ap_si_fwe_p4_1','config_ap_si_fwe_p4','General Studies',1,'subject_general_studies',200,1.00,0.00,NULL,true,'MERIT','{"indicative": "Moderate"}'::jsonb),
  ('section_ts_si_pre_1','config_ts_si_pre','Arithmetic & Test of Reasoning / Mental Ability',1,'subject_reasoning',100,1.00,0.20,NULL,true,'QUALIFYING','{"indicative": "Easy-Moderate"}'::jsonb),
  ('section_ts_si_pre_2','config_ts_si_pre','General Studies',2,'subject_general_studies',100,1.00,0.20,NULL,true,'QUALIFYING','{"indicative": "Easy-Moderate"}'::jsonb),
  ('section_ts_si_fwe_p3_1','config_ts_si_fwe_p3','Arithmetic (SSC standard)',1,'subject_quantitative',100,1.00,0.25,NULL,true,'MERIT','{"indicative": "Moderate"}'::jsonb),
  ('section_ts_si_fwe_p3_2','config_ts_si_fwe_p3','Test of Reasoning / Mental Ability',2,'subject_reasoning',100,1.00,0.25,NULL,true,'MERIT','{"indicative": "Moderate"}'::jsonb),
  ('section_ts_si_fwe_p4_1','config_ts_si_fwe_p4','General Studies',1,'subject_general_studies',200,1.00,0.25,NULL,true,'MERIT','{"indicative": "Moderate"}'::jsonb)
ON CONFLICT DO NOTHING;
