import { useState } from 'react';
import { Link } from 'react-router-dom';
import { useMutation } from '@tanstack/react-query';
import { ArrowLeft, Download, Upload } from 'lucide-react';
import {
  IMPORT_ACCEPTED_EXTENSIONS,
  STUDENT_IMPORT_TEMPLATE_FILENAME,
  XLSX_CONTENT_TYPE,
  type StudentImportPlan,
  type StudentImportRow,
} from '@iace/contracts';
import {
  Alert,
  Badge,
  Button,
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
  FileDropzone,
  LoadingState,
  linkVariants,
  PageHeader,
  StatRow,
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
  TableState,
} from '@iace/ui';
import { api } from '../lib/api';
import { ROUTES } from '../lib/constants';
import { saveBlob } from '../lib/save-blob';

/** Preview, then commit. Three bad rows still import the other 397. */
export function ImportStudentsPage() {
  const [file, setFile] = useState<File | null>(null);
  const [plan, setPlan] = useState<StudentImportPlan | null>(null);

  const preview = useMutation({
    mutationFn: (chosen: File) => api.admin.imports.previewStudents(chosen),
    onSuccess: setPlan,
  });

  const commit = useMutation({
    meta: {
      success: (data: unknown): string => {
        const result = data as { created: number; updated: number; skipped: number };
        return `Imported: ${result.created} created, ${result.updated} updated, ${result.skipped} skipped.`;
      },
    },
    mutationFn: (chosen: File) => api.admin.imports.commitStudents(chosen),
  });

  const sample = useMutation({
    mutationFn: () => api.admin.imports.studentTemplate(),
    onSuccess: (blob) => saveBlob(blob, STUDENT_IMPORT_TEMPLATE_FILENAME),
  });

  /** Choosing a file previews it at once — that is why they chose it. */
  const choose = (chosen: File | undefined) => {
    if (!chosen) return;
    setFile(chosen);
    setPlan(null);
    commit.reset();
    preview.reset();
    preview.mutate(chosen);
  };

  const canCommit =
    file !== null && plan !== null && plan.summary.willCreate + plan.summary.willUpdate > 0;

  return (
    <>
      <Button variant="ghost" size="sm" className="mb-3 -ml-2" asChild>
        <Link to={ROUTES.STUDENTS}>
          <ArrowLeft aria-hidden />
          All students
        </Link>
      </Button>

      <PageHeader
        title="Import students"
        description="Only Mobile Number is required. Each new student is given a starting PIN — the first four digits of their own number — which they should change on first sign-in."
      />

      <div className="grid gap-5 lg:grid-cols-[minmax(0,1fr)_360px]">
        <Card className="order-2 p-4 lg:order-1">
          {plan?.fileErrors.length ? (
            <Alert variant="danger" className="mb-4">
              <span>{plan.fileErrors.join(' ')}</span>
            </Alert>
          ) : null}

          {commit.data ? (
            <Alert variant="success" className="mb-4">
              <span>
                Imported: {commit.data.created} created, {commit.data.updated} updated,{' '}
                {commit.data.skipped} skipped.{' '}
                <Link to={ROUTES.STUDENTS} className={linkVariants({ variant: 'inline' })}>
                  View students
                </Link>
              </span>
            </Alert>
          ) : null}

          <Table>
            <TableHeader>
              <TableRow>
                <TableHead numeric>Line</TableHead>
                <TableHead>Mobile</TableHead>
                <TableHead>Name</TableHead>
                <TableHead>What happens</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              <TableState
                isLoading={false}
                isEmpty={plan === null || plan.rows.length === 0}
                colSpan={5}
                empty={
                  plan === null
                    ? 'Choose an Excel file to see exactly what it would do. Nothing is written until you press Import.'
                    : 'No rows in that file.'
                }
              >
                {plan?.rows.map((row) => (
                  <ImportRow key={row.line} row={row} />
                ))}
              </TableState>
            </TableBody>
          </Table>
        </Card>

        <div className="order-1 flex flex-col gap-4 lg:order-2">
          {/*
            The sample comes first. An admin who has never done this before
            needs the shape of the file before they need anywhere to put one,
            and it is generated by the API from the columns the parser matches
            on — so it cannot describe a format the importer would reject.
          */}
          <Card>
            <CardHeader>
              <CardTitle>Start from the sample</CardTitle>
              <CardDescription>
                An Excel file with the right columns, an example row, and a sheet explaining each
                one. Fill it in and upload it below.
              </CardDescription>
            </CardHeader>
            <CardContent className="flex flex-col gap-2">
              <Button
                variant="outline"
                icon={<Download aria-hidden />}
                loading={sample.isPending}
                onClick={() => sample.mutate()}
              >
                Download sample file
              </Button>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>Your file</CardTitle>
              <CardDescription>
                Excel (.xlsx). A .csv exported from another system works too.
              </CardDescription>
            </CardHeader>
            <CardContent className="flex flex-col gap-3">
              <FileDropzone
                accept={`${IMPORT_ACCEPTED_EXTENSIONS.join(',')},${XLSX_CONTENT_TYPE}`}
                file={file}
                onFileChange={choose}
                hint={IMPORT_ACCEPTED_EXTENSIONS.join(' or ')}
                aria-label="Student import file"
              />

              {preview.isPending ? <LoadingState>Reading the file…</LoadingState> : null}

              <Button
                icon={<Upload aria-hidden />}
                loading={commit.isPending}
                disabled={!canCommit}
                onClick={() => file && commit.mutate(file)}
              >
                Import {plan ? `${plan.summary.willCreate + plan.summary.willUpdate} rows` : ''}
              </Button>
            </CardContent>
          </Card>

          {plan ? (
            <Card>
              <CardHeader>
                <CardTitle>What this would do</CardTitle>
              </CardHeader>
              <CardContent className="flex flex-col gap-2 text-sm">
                <StatRow label="Rows read" value={plan.summary.total} />
                <StatRow label="New students" value={plan.summary.willCreate} />
                <StatRow label="Existing students updated" value={plan.summary.willUpdate} />
                <StatRow label="Skipped (have errors)" value={plan.summary.invalid} />
                <StatRow
                  label="Given a starting PIN"
                  value={plan.rows.filter((row) => row.willReceiveDefaultPin).length}
                />
              </CardContent>
            </Card>
          ) : null}
        </div>
      </div>
    </>
  );
}

function ImportRow({ row }: Readonly<{ row: StudentImportRow }>) {
  return (
    <TableRow>
      <TableCell numeric className="text-muted-foreground">
        {row.line}
      </TableCell>
      <TableCell className="tabular-nums">{row.mobile ?? '—'}</TableCell>
      <TableCell>{row.fullName ?? <span className="text-muted-foreground">—</span>}</TableCell>
      <TableCell>
        {row.action !== 'skip' ? (
          <span className="flex flex-wrap items-center gap-1.5">
            <Badge variant={row.action === 'create' ? 'success' : 'info'}>
              {row.action === 'create' ? 'Create' : 'Update'}
            </Badge>
            {row.willReceiveDefaultPin ? <Badge variant="neutral">+ starting PIN</Badge> : null}
          </span>
        ) : (
          <span className="flex flex-wrap items-center gap-1.5">
            <Badge variant="danger">Skip</Badge>
            <span className="text-xs text-destructive">{row.errors.join('; ')}</span>
          </span>
        )}
      </TableCell>
    </TableRow>
  );
}
