import { useState } from 'react';
import { Link } from 'react-router-dom';
import { useMutation } from '@tanstack/react-query';
import { ArrowLeft, Download, FileUp, Loader2, Upload } from 'lucide-react';
import {
  IMPORT_ACCEPTED_EXTENSIONS,
  STUDENT_IMPORT_TEMPLATE_FILENAME,
  type StudentImportPlan,
  type StudentImportRow,
} from '@iace/contracts';
import {
  Alert,
  Badge,
  Button,
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
  Table,
  TableBody,
  TableCell,
  TableEmpty,
  TableHead,
  TableHeader,
  TableRow,
  linkVariants,
} from '@iace/ui';
import { PageHeader } from '../components/app-shell';
import { api } from '../lib/api';
import { ROUTES } from '../lib/constants';
import { bannerMessage } from '@iace/app-kit';

/**
 * Preview, then commit. Nothing is written until the admin has seen exactly
 * what would happen — and a file with three bad rows still imports the other
 * 397 rather than being refused whole.
 */
export function ImportStudentsPage() {
  const [file, setFile] = useState<File | null>(null);
  const [plan, setPlan] = useState<StudentImportPlan | null>(null);

  const preview = useMutation({
    mutationFn: (chosen: File) => api.admin.imports.previewStudents(chosen),
    onSuccess: setPlan,
  });

  const commit = useMutation({
    mutationFn: (chosen: File) => api.admin.imports.commitStudents(chosen),
  });

  const sample = useMutation({
    mutationFn: () => api.admin.imports.studentTemplate(),
    onSuccess: (blob) => saveBlob(blob, STUDENT_IMPORT_TEMPLATE_FILENAME),
  });

  /**
   * Choosing a file previews it immediately. The two-step "choose, then press
   * Preview" was a button that did nothing an admin had asked for — they
   * picked the file BECAUSE they wanted to see it.
   */
  const choose = (chosen: File | undefined) => {
    if (!chosen) return;
    setFile(chosen);
    setPlan(null);
    commit.reset();
    preview.reset();
    preview.mutate(chosen);
  };

  const canCommit =
    file !== null && plan !== null && plan.summary.willCreate + plan.summary.willUpdate > 0;

  return (
    <>
      <Button variant="ghost" size="sm" className="mb-3 -ml-2" asChild>
        <Link to={ROUTES.STUDENTS}>
          <ArrowLeft aria-hidden />
          All students
        </Link>
      </Button>

      <PageHeader
        title="Import students"
        description="Only Mobile Number is required. Each new student is given a starting PIN — the first four digits of their own number — which they should change on first sign-in."
      />

      <div className="grid gap-5 lg:grid-cols-[minmax(0,1fr)_360px]">
        <Card className="order-2 p-4 lg:order-1">
          {plan?.fileErrors.length ? (
            <Alert variant="danger" className="mb-4">
              <span>{plan.fileErrors.join(' ')}</span>
            </Alert>
          ) : null}

          {commit.data ? (
            <Alert variant="success" className="mb-4">
              <span>
                Imported: {commit.data.created} created, {commit.data.updated} updated,{' '}
                {commit.data.skipped} skipped.{' '}
                <Link to={ROUTES.STUDENTS} className={linkVariants({ variant: 'inline' })}>
                  View students
                </Link>
              </span>
            </Alert>
          ) : null}

          {preview.error ? (
            <Alert variant="danger" className="mb-4">
              {bannerMessage(preview.error)}
            </Alert>
          ) : null}
          {commit.error ? (
            <Alert variant="danger" className="mb-4">
              {bannerMessage(commit.error)}
            </Alert>
          ) : null}

          <Table>
            <TableHeader>
              <TableRow>
                <TableHead numeric>Line</TableHead>
                <TableHead>Mobile</TableHead>
                <TableHead>Name</TableHead>
                <TableHead>Groups</TableHead>
                <TableHead>What happens</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {plan === null ? (
                <TableEmpty colSpan={5}>
                  Choose an Excel file to see exactly what it would do. Nothing is written until you
                  press Import.
                </TableEmpty>
              ) : plan.rows.length === 0 ? (
                <TableEmpty colSpan={5}>No rows in that file.</TableEmpty>
              ) : (
                plan.rows.map((row) => <ImportRow key={row.line} row={row} />)
              )}
            </TableBody>
          </Table>
        </Card>

        <div className="order-1 flex flex-col gap-4 lg:order-2">
          {/*
            The sample comes first. An admin who has never done this before
            needs the shape of the file before they need anywhere to put one,
            and it is generated by the API from the columns the parser matches
            on — so it cannot describe a format the importer would reject.
          */}
          <Card>
            <CardHeader>
              <CardTitle>Start from the sample</CardTitle>
              <CardDescription>
                An Excel file with the right columns, an example row, and a sheet explaining each
                one. Fill it in and upload it below.
              </CardDescription>
            </CardHeader>
            <CardContent className="flex flex-col gap-2">
              <Button variant="outline" disabled={sample.isPending} onClick={() => sample.mutate()}>
                {sample.isPending ? (
                  <Loader2 className="animate-spin" aria-hidden />
                ) : (
                  <Download aria-hidden />
                )}
                Download sample file
              </Button>
              {sample.error ? <Alert variant="danger">{bannerMessage(sample.error)}</Alert> : null}
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>Your file</CardTitle>
              <CardDescription>
                Excel (.xlsx). A .csv exported from another system works too.
              </CardDescription>
            </CardHeader>
            <CardContent className="flex flex-col gap-3">
              <label className="flex cursor-pointer flex-col items-center justify-center gap-1 rounded-md border border-dashed border-border px-3 py-6 text-center text-sm text-muted-foreground transition-colors hover:border-ring hover:text-foreground">
                <FileUp className="size-5" aria-hidden />
                <span className="font-medium text-foreground">
                  {file ? file.name : 'Choose a file'}
                </span>
                <span className="text-xs">
                  {file
                    ? `${(file.size / 1024).toFixed(0)} KB — choose another to replace it`
                    : IMPORT_ACCEPTED_EXTENSIONS.join(' or ')}
                </span>
                <input
                  type="file"
                  accept={`${IMPORT_ACCEPTED_EXTENSIONS.join(',')},${XLSX_MIME}`}
                  className="sr-only"
                  onChange={(event) => {
                    choose(event.target.files?.[0]);
                    // Cleared so choosing the SAME file again still fires: the
                    // admin has usually just fixed it and saved over the top.
                    event.target.value = '';
                  }}
                />
              </label>

              {preview.isPending ? (
                <p className="flex items-center gap-2 text-sm text-muted-foreground">
                  <Loader2 className="size-4 animate-spin" aria-hidden />
                  Reading the file…
                </p>
              ) : null}

              <Button
                disabled={!canCommit || commit.isPending}
                onClick={() => file && commit.mutate(file)}
              >
                {commit.isPending ? (
                  <Loader2 className="animate-spin" aria-hidden />
                ) : (
                  <Upload aria-hidden />
                )}
                Import {plan ? `${plan.summary.willCreate + plan.summary.willUpdate} rows` : ''}
              </Button>
            </CardContent>
          </Card>

          {plan ? (
            <Card>
              <CardHeader>
                <CardTitle>What this would do</CardTitle>
              </CardHeader>
              <CardContent className="flex flex-col gap-2 text-sm">
                <Summary label="Rows read" value={plan.summary.total} />
                <Summary label="New students" value={plan.summary.willCreate} />
                <Summary label="Existing students updated" value={plan.summary.willUpdate} />
                <Summary label="Skipped (have errors)" value={plan.summary.invalid} />
                <Summary
                  label="Given a starting PIN"
                  value={plan.rows.filter((row) => row.willReceiveDefaultPin).length}
                />
              </CardContent>
            </Card>
          ) : null}
        </div>
      </div>
    </>
  );
}

function Summary({ label, value }: { label: string; value: number }) {
  return (
    <div className="flex items-center justify-between gap-4">
      <span className="text-muted-foreground">{label}</span>
      <span className="font-medium tabular-nums text-foreground">{value}</span>
    </div>
  );
}

function ImportRow({ row }: { row: StudentImportRow }) {
  return (
    <TableRow>
      <TableCell numeric className="text-muted-foreground">
        {row.line}
      </TableCell>
      <TableCell className="tabular-nums">{row.mobile ?? '—'}</TableCell>
      <TableCell>{row.fullName ?? <span className="text-muted-foreground">—</span>}</TableCell>
      <TableCell className="text-muted-foreground">
        {row.groupNames.length ? row.groupNames.join(', ') : '—'}
      </TableCell>
      <TableCell>
        {row.action === 'create' ? (
          <span className="flex flex-wrap items-center gap-1.5">
            <Badge variant="success">Create</Badge>
            {row.willReceiveDefaultPin ? <Badge variant="neutral">+ starting PIN</Badge> : null}
          </span>
        ) : row.action === 'update' ? (
          <span className="flex flex-wrap items-center gap-1.5">
            <Badge variant="info">Update</Badge>
            {row.willReceiveDefaultPin ? <Badge variant="neutral">+ starting PIN</Badge> : null}
          </span>
        ) : (
          <span className="flex flex-wrap items-center gap-1.5">
            <Badge variant="danger">Skip</Badge>
            <span className="text-xs text-destructive">{row.errors.join('; ')}</span>
          </span>
        )}
      </TableCell>
    </TableRow>
  );
}

/** What the file picker offers alongside the extensions. */
const XLSX_MIME = 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet';

/**
 * Hands a downloaded file to the browser.
 *
 * The sample cannot be a plain <a href>: the endpoint is authenticated, and a
 * bare link sends no Authorization header — it would download a 401 body saved
 * as a .xlsx, which opens as a corrupt file rather than an error.
 */
function saveBlob(blob: Blob, filename: string): void {
  const href = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = href;
  link.download = filename;
  document.body.append(link);
  link.click();
  link.remove();
  URL.revokeObjectURL(href);
}
